In [3]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Import datasets, classifiers and performance metrics
from sklearn import datasets, svm, metrics

# The digits dataset
train=pd.read_csv('C://Jainam/Fall 18/EE 551/all/train.csv')
data_test=pd.read_csv('C://Jainam/Fall 18/EE 551/all/test.csv')
#trainnum=20000
#testnum=20000

#data_train= train.iloc[:trainnum,1:].values
#label_train=train.iloc[:trainnum,0].values

#data_test= train.iloc[trainnum:trainnum+testnum,1:].values
#label_test= train.iloc[trainnum:trainnum+testnum,0].values

data_train=train.iloc[:,1:].values
label_train=train.iloc[:,0].values

data_test=data_test.values
	
data_train[data_train>0]=1
data_test[data_test>0]=1

print(data_train)
print(label_train)
# Create a classifier: a support vector classifier
classifier = svm.SVC(C=200,kernel='rbf',gamma=0.01,cache_size=8000,probability=False)
#classifier = svm.SVC()


# We learn the digits on the first half of the digits
classifier.fit(data_train, label_train)

# Now predict the value of the digit on the second half:
#expected = label_test
predicted = classifier.predict(data_test)

'''print("Classification report for classifier %s:\n%s\n"
      % (classifier, metrics.classification_report(expected, predicted)))
print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))'''

#print(expected)
df=pd.DataFrame(predicted)
df.index+=1
df.index.name='ImageId'
df.columns=['Label']
df.to_csv('results.csv',header=True)
print(predicted)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[1 0 1 ... 7 6 9]


KeyboardInterrupt: 

In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
# from sklearn import cross_validation
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
# from nolearn.dbn import DBN
import timeit

In [11]:
train = pd.read_csv("C://Jainam/Fall 18/EE 551/all/train.csv")
features = train.columns[1:]
X = train[features]
y = train['label']
X_train, X_test, y_train, y_test = train_test_split(X/255.,y,test_size=0.1,random_state=0)

In [13]:
clf_rf = RandomForestClassifier()
clf_rf.fit(X_train, y_train)
y_pred_rf = clf_rf.predict(X_test)
acc_rf = accuracy_score(y_test, y_pred_rf)
print ("random forest accuracy: ",acc_rf)

c:\users\jaina\appdata\local\programs\python\python36\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


random forest accuracy:  0.9385714285714286


In [14]:
clf_sgd = SGDClassifier()
clf_sgd.fit(X_train, y_train)
y_pred_sgd = clf_sgd.predict(X_test)
acc_sgd = accuracy_score(y_test, y_pred_sgd)
print ("stochastic gradient descent accuracy: "),acc_sgd

c:\users\jaina\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


stochastic gradient descent accuracy: 


(None, 0.8897619047619048)

In [16]:
clf_svm = LinearSVC()
clf_svm.fit(X_train, y_train)
y_pred_svm = clf_svm.predict(X_test)
acc_svm = accuracy_score(y_test, y_pred_svm)
print ("Linear SVM accuracy: ",acc_svm)

Linear SVM accuracy:  0.9102380952380953


c:\users\jaina\appdata\local\programs\python\python36\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [17]:
clf_knn = KNeighborsClassifier()
clf_knn.fit(X_train, y_train)
y_pred_knn = clf_knn.predict(X_test)
acc_knn = accuracy_score(y_test, y_pred_knn)
print ("nearest neighbors accuracy: ",acc_knn)

nearest neighbors accuracy:  0.9666666666666667
